
# Use the Node.js LTS image as a base
FROM node:lts
RUN npm install nodemon -g

# Copy application to src directory then set working directory to /src
COPY . /src
WORKDIR /src

# Install dependencies, expose port 3000, then start the application
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]